---	
# MetalLB test	
apiVersion: v1	
kind: Service	
metadata:	
  name: nginx-svc	
spec:	
  selector:	
    app: nginx	
  ports:	
  - protocol: TCP	
    port: 80	
    targetPort: 80	
  type: LoadBalancer	
  loadBalancerIP: 192.168.1.235

---	
apiVersion: apps/v1	
kind: Deployment	
metadata:	
  name: nginx	
spec:	
  selector:	
    matchLabels:	
      app: nginx	
  replicas: 2	
  template:	
    metadata:	
      labels:	
        app: nginx	
    spec:	
      containers:	
      - name: nginx	
        image: nginx:1.14.2	
        ports:	
        - containerPort: 80	
