---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: nginx
  rules:
  - host: raspi-gou.local
    http:
      paths:
      - pathType: Prefix
        path: "/nextcloud"
        backend:
          service:
            name: nextcloud-release
            port:
              number: 80