---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-deployment
  template:
    metadata:
      labels:
        app: nextcloud-deployment
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:28.0.1-apache
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: "nextcloud-mysql-service" 
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: NEXTCLOUD_ADMIN_USER
          value: "admin"
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: "admin"
      - name: mysql
        image: mysql:8.0.34
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: TZ
          value: "Asia/Tokyo"

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  type: NodePort
  selector:
    app: nextcloud-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mysql-service
spec:
  selector:
    app: nextcloud-deployment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

